travis:
  secure:
    BINSTAR_TOKEN: NZBJ56krJL3uWKaXRQgdYYLodsQAqlIy1ZYHaukjXG+BZKyW6iT8gVTPtnZR+d2anyzHhE6I6ODz6H2oe/bRH4pO77nmi204WbVO7Be1lG9peMdGWRs5BPiCMLwJzH3/6DUw7HRcjXWvPa+usWjsIhs66eTWS+5hwQbPufetymX2Fw5hFzEnJbi0EuWqzUfdD2bA6QwfZoyX8h/lN3aeZTNXVRWY7UyiPFYPsWa+T727iik/YIGyWToXzyV0JDj8000Z6NCRQI7t3Hh/s7uOjFDheH+thxFyR0KIXMq9xW2RcMuHT7RTDY6WLDY1V6C1WM+S1WM1N43i4PtVkcR14coHtil06JOG22XCUDXTh/4xwY2UKvaB13Tk8SMdtOUPDh+B+YaeL4KvIL+Y9SFqM7OfCMJsc+z5mr3mr+HmcZ+O+/xfV2zoBGsfF2TQcYSCzsM+D8NjuK5kdjzGD6rjzHNT51GQ0IfaBrI6f9cTHudRnBy33xGmxbR401qZ17yr+QOV3ADuSan/6K8Z4qw1goT3h7ijb1MuL8Rn9tXafuNYerBhi3W6Kn8hXjg9ohOf9XhtSCgYT2Z0ds16XLJanLd/1kwXV9D2evnMU7KghVw+rDghsvfVYJJaVrLrc0kv+KHq6ROyUfmvKtOtzYaWSDrCic1/B0Tqw+AxHuVC9eQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
