travis:
  secure:
    BINSTAR_TOKEN: YPLP1tGkYebsRhp2EL7NInD6cQddVhDQWrEGGosrIORYQqLNHp0pYcKUqfZK2Vb9jKYV9YuURqUmitKg1oVb7r5HWrVZBImgszh0ZHtn8s1JjIbKSSGt7Mx4LutHXJzbAB6sOw0+zBGdRLSLbvBe+F17G9dP08GkUh43yUGmB8394ZGo4vNdEBoUxcwxhbGT8OYttyrxyo8hOp55CzmqidhZ62ynDf+W9t6yeOC0eHgfdMIp1DVyDnMS5Ttjeqf6UHgxjWuNM99U2gdQnNGHeU/Om8dGyJcKJ7JHaQTd0L9CE3BPVBgGpV90YXKqZwBUdn5xdZ17pKNMXZYEBZi7OYAaDxTN6UHISv6NQ6EdCfJS0sVDOEnwJIhyAWBYsXAN5lwKcrywr184GpZN4qUK396hJZfnk4Zni23WTBqcb7LPHPPMpFIdeOH0B0KeRr1a7833XO9pUN42xcT03y7g18p0ObqkXZwMBY8+2pPhVnwMjeLfA4klqGoVuX+LG4mmhwKBkKwz0EcTDwNRj9Kgxy+7JZRjWwwMKNWrfbduKwF3pPwkO4ikft++Gw7TTTDxK3O+XZaTkh0lSwPCyb3KFx9Nhj7TEK0j+Xmq3AuI7LceOUjyPE1yeojBbKCcGBx7XZ0enxoMhpdZ4qeOnmimBuqpeh6ytRZyI6PMB37mVtk=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
